main: fr.martinfimbel.Minecraft_NewSwitch.SWPlugin
name: minecraft-newswitch
version: 1.0-SNAPSHOT
api-version: 1.13

description:
commands:

  sw:
    description:
    permission: SWPlugin.permission