main: fr.martinfimbel.Minecraft_NewSwitch.SWPlugin
name: minecraft-newswitch
version: 1.0-SNAPSHOT
api-version: 1.13
depend: [minecraft-border]

description:
commands:
  sw:
    description: Switch game configuration command
    permission: SWPlugin.permission